### PR TITLE
Add AltStore to Android

### PR DESCRIPTION
**Pull request by Xmemes811**
We want AltStore on Android right now! We wait until the app ha released.

### CODE REVIEW

**Comment by coolfloppa** [comment]
AltStore was made for iOS devices, not Android. There's no point of releasing a build for Android.

**Comment by JoeMatt** [comment]
this isn't even a pull request. close this before you embarrass yourself further.

**Comment by devinprater** [comment]
Please use F-droid instead. It's made for Android, and has all the Foss
apps you could want. That's basically what AltStore does, adds another
store to iOS, except it doesn't really have a primary repo of every
developer's app there, you have to add other repos manually.
Devin Prater
***@***.***

**Comment by cootshk** [comment]
you can just install an apk manually without an app like this
plus most of these apps have equivalents (or straight up ports like dolphin) on the google play store
plus iphones are just superior to android phones

**Comment by SamuelChih** [comment]
It would be great if AltServer is on Android, and able to connect my iPad with Android phone with wi-fi or cable and refresh app this way.

**Comment by wyldcrd** [comment]
It’s possible to run a windows/macOS version of iTunes/iCloud on an android device but I’m pretty sure trying to get it to work would be a metric sized pain in the development buttcheek. (Wine for android exists but thinking about it gives me a headache)

If refreshing away from your main pc is important I personally would recommend sidestore. It is a fork that provides the same features but with the added benefit of being able to refresh off of a server in the cloud. This brings up security risks but you can host your own sideserver instead of relying on sidestore’s if you worry about security.

**Comment by wyldcrd** [comment]
For future reference altserver requires iCloud/iTunes.

**Comment by lonkelle** [comment]
Anyone wanting something like this should follow @devinprater's advice. "AltStore on Android" is F-Droid for all intents and purposes. Closing this.

**Comment by Lncvrt** [comment]
what tf is the point of altstore for android if you can just install a .apk directly...

**Pull request closed without merging**
