### PR TITLE
1.5

### PR DESCRIPTION
**Pull request by eliekh05**
linux support

### CODE REVIEW

**Comment by noah978** [comment]
Last I checked, you can't run an iOS app on Linux...

**Comment by wyldcrd** [comment]
First android support and now Linux?
Linux and Android have their own package managers and altstores.

Now if you are talking about refreshing apps, altserver has a Linux version now.

**Comment by wyldcrd** [comment]
https://github.com/NyaMisty/AltServer-Linux

**Comment by wyldcrd** [comment]
As for refreshing through android, just use sidestore.

**Pull request closed without merging**
